sudo: false
language: ruby
cache: bundler
rvm:
- 2.6.6
before_install: gem install bundler
deploy:
  provider: heroku
  api_key:
    secure: nckwCfR+ABLBF9wEG5zqpRdR4C3wC1iqM4Y1Ymj6bh3uIHRLRfZo4G05FxLECCaqrtzrGpUQU9mGMdZ+RJM2+C7JqjWGmebFwZS8j7e+mGFxJ9EbmcPgrvX85zH7vWpOpZbTIOMQb0nZrL4Kst8tvRSOiKKlqKwV6sW58bdbzC0Vku6tBl0YQZtQ3qjxnrUQwAEUZxEFqk5wAulLcbDDVTN/NncWYBbl9bkYYPRds+ON3iX8lTGdwcTyUxOd+3UKV6g44s+04bvRRVrH1yy3uJJ1KigMoIKnIhBs5mxwzwUFsvq8fnPUqp2DKtECj+zlMgYnkLFunYxE6EDO1Dk42NzvHPNkADoKbP17IaLTgLNpA/DepUqn8MZqysAUUXur+20p4wAq38FJin3AqJZ4DSCBCDKpxxw+0nkK39bPFbJQOJP+4b0rgxmw8ZAJ9tXw7MMw6meCLREqd/evgL4u1bLL0FDszY+brdLBbSRmlWkqoyUNfwd0wOfMCe5ixV9qFxojyzeyvftXAHedyqYOgQ0T5FYfop32IW0dseOh6l6oiFbwUTFYvdp07oaRk7FbdGy/EmLAhaCIyYbarLNGZp11JbOnnMo1e0jyuuUDrzUVhI7fGdH050Y6XHpqTjOX0WU/1k05ydeZ/fB49AybZfJaYfwyarEH3Yr83Pfa8Rw=
