sudo: false
language: ruby
cache: bundler
rvm:
- 2.6.6
before_install: gem install bundler
deploy:
  provider: heroku
  api_key:
    secure: uTxey081Yja47hzIm+/0lGU7mh+jBE8lNk1FUp6Y3eA4e23J1+vz2oFo/rkOty3jZRREbuCslpT+vnPvOcx9g5ensy0DLOLGxSCFpEf1+DL/4JxxFI+4cHwSyinkOGUouF8HGXB0nhfgWnDMNwNmasC2TVit3jKk3jc5vvidtudnTit0sQpRubFAJDt/7A4CAqYBRjE8u3CAME1+PQnXl1PRFVY1lUC0xjO47ZynIKvHMjKqEuR6oRQAyv2lwz0k912Ydcy91hD/SryPH9ZlWYO9H1lAKDcmecEOf/53oZ8j4BbG7AN6MXbJvt36z2uLSxZMiMoXr0V8CctBx59zhrscM4hCD/ExAXqa6mf4swbh96/x/qkkyA1HoAHTm/9KV7vRDYRWGHXIwll15Erz+2lFEzMIjiX7yODSkGEXQnSoGkf53KcdIn4Z9R7qLPDgsiywWOTrvtEYrdaeB4IEIgU303ucB4vVkQoBNPBbQmov7PAY+5rPGIRihGEzDyAfnU/dxTEL5M2XKhcVwEbLcKP0yie6XDjDZ94eTBB4fRZtcyjBE4mYxWPAoTm8SfZx+VfS3P1DV6emvy5NI4VzkFzR3NMc7oeTzTmHohdt9IR2m62Thz3daugwDbE7zig1jMxqFtD/OqkuTsA+22yMFCPPKh/H6GNhJGSAwaDXw7I=
