# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e2e9320eb6ecd3b2c2663b7749cf4ebf1980ba7a9c27de96e8b5ecaf5baf3aec84adefc729f4733d49ac9848ccaab9b1ec05886cde67973674c8361e983fba3d

test:
  secret_key_base: 4563f653223310ce45ed247dc5ae1afd09fce16ce4e3516e1b7c244e14d21ab4c8cf56b71be0a1f49e95e4e08ceade6908341c3e4eb5f11418f7fcd9f62c6a42

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
